name: Publish dotnet package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push NuGetPackageAnalyzer/bin/Release/*.nupkg
